global using Microsoft.AspNetCore.Identity;
global using System;
global using System.Collections.Generic;
global using Chatverse.Domain.Entities;
global using Chatverse.Domain.Enums;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Chatverse.Domain.Common;
global using Chatverse.Domain.Identity;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using static System.Runtime.InteropServices.JavaScript.JSType;
global using static System.Net.Mime.MediaTypeNames;
global using System.ComponentModel.DataAnnotations;
